version: '3.9'
services:
  php:
    # image: php:8-alpine
    image: php_ex2_image
    working_dir: '/home/php/myproject'
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    command: '/bin/sh'
    tty: true
    stdin_open: true
    stop_signal: SIGKILL
    user: ${U:-root}:${G:-root}
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password123456
    volumes:
      - ./:/home/php/myproject
    ports:
      - '${PORT:-8000}:${PORT:-8000}'
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: password123456
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password123456
    # ports:
    #     - ${DB_PORT:-3306}:3306
    volumes:
      - mysqldata:/var/lib/mysql
  myadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password123456
    depends_on:
      - db
    # restart: always
    ports:
      - ${MY_ADMIN_PORT:-8081}:80
volumes:
  mysqldata:
